name: Factorial Tester
on: [pull_request]
jobs:
  test-factorial:
    runs-on: ubuntu-latest
    env:
      DOCKER_FILE: github/workspace/Dockerfile
    steps:
      - name: build docker image
        run: docker build -t test/test github/workspace/.
      - name: run test
        run: docker run test/test
